import type { Metadata } from 'next'
import { HStack } from '@chakra-ui/react'

export const metadata: Metadata = {
	title: 'Portfolio',
	description: 'Generated by create next app'
}

export default function Portfolio() {
	return (
		<div style={{ backgroundColor: 'red' }}>
			<HStack bgColor='#040427'>red</HStack>
		</div>
	)
}
