'use client'

import type { Metadata } from 'next'
import { Heading, Stat, StatArrow, StatGroup, StatHelpText, StatLabel, StatNumber, Tooltip } from '@chakra-ui/react'
import { IoMdInformationCircleOutline } from 'react-icons/io'
import { Table1 } from '@/components/table/table'

/*export const metadata: Metadata = {
	title: 'Portfolio',
	description: 'Generated by create next app'
}*/

const columns: any = [
	{
		header: 'title',
		accessorKey: 'title',
		sortable: true,
		cell: ({ row }: { row: any }) => {
			return <div>{row.original.title}</div>
		}
	},
	{
		header: 'quantity',
		accessorKey: 'quantity',
		sortable: true,
		cell: ({ row }: { row: any }) => {
			return <div>{row.original.quantity}</div>
		}
	},
	{
		header: 'Average price',
		accessorKey: 'averagePrice',
		sortable: true,
		cell: ({ row }: { row: any }) => {
			return <div>{row.original.averagePrice}</div>
		}
	},
	{
		header: 'Current price',
		accessorKey: 'currentPrice',
		sortable: true,
		cell: ({ row }: { row: any }) => {
			return <div>{row.original.currentPrice}</div>
		}
	},
	{
		header: 'Current value',
		accessorKey: 'currentValue',
		sortable: true,
		cell: ({ row }: { row: any }) => {
			return <div>{row.original.currentValue}</div>
		}
	},
	{
		header: 'Current profit',
		accessorKey: 'currentProfit',
		sortable: true,
		cell: ({ row }: { row: any }) => {
			return <div>{row.original.currentProfit}</div>
		}
	},
	{
		header: 'Total profit',
		accessorKey: 'totalProfit',
		sortable: true,
		cell: ({ row }: { row: any }) => {
			return <div>{row.original.totalProfit}</div>
		}
	},
	{
		header: 'Share',
		accessorKey: 'share',
		sortable: true,
		cell: ({ row }: { row: any }) => {
			return <div>{row.original.share}</div>
		}
	}
]

export default function Portfolio() {
	const data = [
		{
			id: 11,
			name: 'voo',
			title: 'S&P 500 ETF',
			ticker: 'VOO',
			quantity: 4,
			averagePrice: 30940.08,
			currentPrice: 39469.25,
			currentValue: 157876.99,
			currentProfit: 27.57,
			totalProfit: 34116.68,
			share: 50
		},
		{
			id: 12,
			name: 'spdw',
			title: 'Portfolio Developed World ex-US ETF',
			ticker: 'SPDW',
			quantity: 44,
			averagePrice: 2970.32,
			currentPrice: 3247.02,
			currentValue: 138846.35,
			currentProfit: 15.24,
			totalProfit: 24156.82,
			share: 30
		},
		{
			id: 13,
			name: 'iemg',
			title: 'iShares Core MSCI Emerging Markets ETF',
			ticker: 'IEMG',
			quantity: 27,
			averagePrice: 4478.22,
			currentPrice: 4995.58,
			currentValue: 127860.92,
			currentProfit: 7.51,
			totalProfit: 14163.61,
			share: 20
		}
	]

	return (
		<div style={{ width: '100%', height: '100%', padding: '16px' }}>
			<StatGroup w='full' h='fit-content' p={4} bgColor='#040427' color='white'>
				<Stat minW={138} pl={4}>
					<StatLabel display='flex' alignItems='center' gap={1}>
						<p>Price</p>
						<Tooltip
							p={2}
							bgColor='white'
							color='gray.700'
							fontSize={12}
							label='The sum of the current market value of all portfolio assets: stocks, bonds, cash. The current value of bonds takes into account the NCD that you will receive when you sell the security or pay when you buy back a short position. At the same time, the value of shares denominated in currency is recalculated at the current ruble exchange rate. Below is the total value of the portfolio converted in dollars at the current exchange rate.'
						>
							<span>
								<IoMdInformationCircleOutline />
							</span>
						</Tooltip>
					</StatLabel>
					<StatNumber>157 876.99 ₽</StatNumber>
					<StatHelpText>1747.20 $</StatHelpText>
				</Stat>
				<Stat minW={138} pl={4}>
					<StatLabel display='flex' alignItems='center' gap={1}>
						<p>Total profit</p>
						<Tooltip
							p={2}
							bgColor='white'
							color='gray.700'
							fontSize={12}
							label='Profit generated by the assets of the portfolio over its entire time. It includes profit from previous transactions (the security was bought cheaper and sold more expensive), paid dividends and coupons, variation margin, current profit (the security was bought cheaper and went up in price, but has not been sold yet). The sum on transactions with the type of Expenditure and Income. Cash input and withdrawal do not affect the portfolio profit.'
						>
							<span>
								<IoMdInformationCircleOutline />
							</span>
						</Tooltip>
					</StatLabel>
					<StatNumber>34 116.68 ₽</StatNumber>
					<StatHelpText>
						<StatArrow type='increase' />
						27.57 %
					</StatHelpText>
				</Stat>
				<Stat minW={138} pl={4}>
					<StatLabel display='flex' alignItems='center' gap={1}>
						<p>Profitability</p>
						<Tooltip
							p={2}
							bgColor='white'
							color='gray.700'
							fontSize={12}
							label='Yield in per cent per annum is calculated from the date of the first transaction in the portfolio to the current moment. If the investment term is less than one year, a period of 365 days is taken for calculations. The calculation is based on the XIRR method. (internal rate of return on cash flow).'
						>
							<span>
								<IoMdInformationCircleOutline />
							</span>
						</Tooltip>
					</StatLabel>
					<StatNumber>27.57 %</StatNumber>
				</Stat>
				<Stat minW={138} pl={4}>
					<StatLabel display='flex' alignItems='center' gap={1}>
						<p>Change per day</p>
						<Tooltip
							p={2}
							bgColor='white'
							color='gray.700'
							fontSize={12}
							label='Indicates by how much the total value of the portfolio has changed over the last trading day. This difference arises due to changes in the exchange price of the assets included in the portfolio.'
						>
							<span>
								<IoMdInformationCircleOutline />
							</span>
						</Tooltip>
					</StatLabel>
					<StatNumber>1310,37 ₽</StatNumber>
					<StatHelpText>
						<StatArrow type='decrease' />
						0.83 %
					</StatHelpText>
				</Stat>
			</StatGroup>
			<Heading as='h2' size='md' mt={8} mb={4}>
				Portfolio structure
			</Heading>
			<Table1 data={data} columns={columns} />
		</div>
	)
}
