import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Transactions',
	description: 'Generated by create next app'
}

export default function Transactions() {
	return <main>Transactions</main>
}
