'use client'

import type { Metadata } from 'next'
import {
	Box,
	Button,
	Card,
	CardBody,
	Heading,
	Icon,
	Stack,
	StackDivider,
	Text,
	useColorMode,
	useColorModeValue
} from '@chakra-ui/react'
import { useRouter } from 'next/navigation'
import { FaMoon } from 'react-icons/fa'
import { FaArrowLeft, FaLightbulb } from 'react-icons/fa6'
import { FaGear } from 'react-icons/fa6'

/*export const metadata: Metadata = {
	title: 'Interface',
	description: 'Generated by create next app'
}*/

export default function Interface() {
	const router = useRouter()

	const { setColorMode } = useColorMode()

	const bg = useColorModeValue('white', '#21232f')

	return (
		<main style={{ marginTop: '16px' }}>
			<Heading
				as='h1'
				size='md'
				mb={4}
				display='flex'
				alignItems='center'
				gap={2}
				onClick={() => router.push('/profile')}
			>
				<Icon as={FaArrowLeft} w={5} h={5} />
				Interface settings
			</Heading>
			<Card p={6}>
				<CardBody p={0}>
					<Stack divider={<StackDivider />} spacing='4'>
						<Box>
							<Text fontSize='sm' mb={2} color='gray'>
								Interface theme settings
							</Text>
							<Box>
								<Button
									leftIcon={<FaMoon />}
									pl={0}
									variant='ghost'
									_hover={{ bgColor: 'inherit' }}
									onClick={() => setColorMode('dark')}
								>
									Dark theme
								</Button>
								<Button
									leftIcon={<FaLightbulb />}
									pl={0}
									variant='ghost'
									_hover={{ bgColor: 'inherit' }}
									onClick={() => setColorMode('light')}
								>
									Light theme
								</Button>
								<Button
									leftIcon={<FaGear />}
									pl={0}
									variant='ghost'
									_hover={{ bgColor: 'inherit' }}
									onClick={() => setColorMode('system')}
								>
									System theme
								</Button>
							</Box>
						</Box>
					</Stack>
				</CardBody>
			</Card>
		</main>
	)
}
