import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
import './globals.css'
import { fonts } from './fonts'
import { Providers } from '@/app/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Converter funds App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang='en' className={fonts.rubik.variable}>
			<body className={inter.className}>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
