import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Analytics',
	description: 'Generated by create next app'
}

export default function Analytics() {
	return <main>analytics</main>
}
