'use client'

import { Card, CardBody, CardHeader, Heading, ListItem, Stack, Divider, UnorderedList, Icon } from '@chakra-ui/react'
import type { Metadata } from 'next'
import { useRouter } from 'next/navigation'
import { FaDisplay } from 'react-icons/fa6'

/*export const metadata: Metadata = {
	title: 'Profile',
	description: 'Generated by create next app'
}*/

export default function Profile() {
	const router = useRouter()

	return (
		<main style={{ marginTop: '16px' }}>
			<Heading as='h1' size='md' mb={4}>
				Profile
			</Heading>
			<Card onClick={() => router.push('/profile/interface')}>
				<CardHeader display='flex' gap={4}>
					<Icon as={FaDisplay} w={6} h={6} />
					<Heading size='sm' fontWeight={400}>
						Interface settings
					</Heading>
				</CardHeader>
				<CardBody pt={0}>
					<Stack spacing='4'>
						<Divider />
						<UnorderedList>
							<ListItem>Theme selection</ListItem>
						</UnorderedList>
					</Stack>
				</CardBody>
			</Card>
		</main>
	)
}
