'use client'

import { Box, Card, CardBody, CardHeader, Heading, Stack, StackDivider, Text } from '@chakra-ui/react'
import type { Metadata } from 'next'
import { useRouter } from 'next/navigation'

/*export const metadata: Metadata = {
	title: 'Profile',
	description: 'Generated by create next app'
}*/

export default function Profile() {
	const router = useRouter()

	return (
		<main style={{ marginTop: '16px' }}>
			<Heading as='h2' size='md' mb={4}>
				Profile
			</Heading>
			<Card onClick={() => router.push('/profile/interface')}>
				<CardHeader>
					<Heading size='md'>Interface settings</Heading>
				</CardHeader>
				<CardBody pt={0}>
					<Stack divider={<StackDivider />} spacing='4'>
						<Box>
							<Text pt='2' fontSize='sm'>
								theme selection
							</Text>
						</Box>
					</Stack>
				</CardBody>
			</Card>
		</main>
	)
}
