import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Profile',
	description: 'Generated by create next app'
}

export default function Profile() {
	return <main>Profile</main>
}
